#### 1 문제 설명

프로그래머스 모바일은 개인정보 보호를 위해 고지서를 보낼 때 고객들의 전화번호의 일부를 가립니다.
전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 제외한 나머지 숫자를 전부 *으로 가린 문자열을 리턴하는 함수, solution을 완성해주세요.

[제한 조건]
s는 길이 4 이상, 20이하인 문자열입니다.

[입출력 예]

|phone_number|return|
|----|----|
|01033334444|*******4444|
|027778888|*****8888|

In [50]:
def solution(phone_number):
    import numpy as np
    
    if 4 <= len(phone_number) <= 20:
        pns = ''
        for n in range(len(phone_number[:-4])):
            pns += '*'
        answer = pns + phone_number[-4:]
    else:
        print('phone number must be 4 to 20 numbers')
        answer = ''
    
    return answer

In [51]:
solution('01033334444')

'*******4444'

In [52]:
solution('027778888')

'*****8888'

#### 채점 결과

정확성: 50.0

효율성: 0.0

합계: 50.0 / 50

#### 2 문제 설명
함수 solution은 정수 x와 자연수 n을 입력 받아, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 리턴해야 합니다. 다음 제한 조건을 보고, 조건을 만족하는 함수, solution을 완성해주세요.


[제한 조건]

x는 -10000000 이상, 10000000 이하인 정수입니다.
n은 1000 이하인 자연수입니다.


[입출력 예]

|x	|n	|answer|
|--|--|--|
|2	|5	|[2,4,6,8,10]|
|4	|3	|[4,8,12]|
|-4	|2	|[-4, -8]|

In [44]:
def solution(x, n):
    answer = []
    a = x
    while len(answer) < n:
        answer.append(a)
        a += x
    return answer

In [45]:
solution(2, 5)

[2, 4, 6, 8, 10]

In [47]:
solution(4, 3)

[4, 8, 12]

In [48]:
solution(-4, 2)

[-4, -8]

#### 채점 결과
정확성: 50.0

효율성: 0.0

합계: 50.0 / 50

### 3 문제 설명
땅따먹기 게임을 하려고 합니다. 땅따먹기 게임의 땅(land)은 총 N행 4열로 이루어져 있고, 모든 칸에는 점수가 쓰여 있습니다. 1행부터 땅을 밟으며 한 행씩 내려올 때, 각 행의 4칸 중 한 칸만 밟으면서 내려와야 합니다. 단, 땅따먹기 게임에는 한 행씩 내려올 때, 같은 열을 연속해서 밟을 수 없는 특수 규칙이 있습니다.

예를 들면,

| 1 | 2 | 3 | 5 |

| 5 | 6 | 7 | 8 |

| 4 | 3 | 2 | 1 |

로 땅이 주어졌다면, 1행에서 네번째 칸 (5)를 밟았으면, 2행의 네번째 칸 (8)은 밟을 수 없습니다.

마지막 행까지 모두 내려왔을 때, 얻을 수 있는 점수의 최대값을 return하는 solution 함수를 완성해 주세요. 위 예의 경우, 1행의 네번째 칸 (5), 2행의 세번째 칸 (7), 3행의 첫번째 칸 (4) 땅을 밟아 16점이 최고점이 되므로 16을 return 하면 됩니다.

제한사항
행의 개수 N : 100,000 이하의 자연수
열의 개수는 4개이고, 땅(land)은 2차원 배열로 주어집니다.
점수 : 100 이하의 자연수
입출력 예

|land|	answer|
|---|---|
|[[1,2,3,5],[5,6,7,8],[4,3,2,1]]	|16|

입출력 예 설명
입출력 예 #1
문제의 예시와 같습니다.

In [99]:
import random
import numpy as np
n = 3
ls = random.choices(range(1, 100), k=4*n)
land = np.array(ls).reshape(n, 4)
land

array([[91, 59, 97, 32],
       [65, 59, 96, 87],
       [99, 24, 84, 14]])

In [116]:
answer = 0
value = []
for i in range(n):
    answer += land[i, :].max()
    value.append(land[i, :].max())
answer, value

(292, [97, 96, 99])

In [127]:
for i in range(n*4):
    print(i, i % 4)

0 0
1 1
2 2
3 3
4 0
5 1
6 2
7 3
8 0
9 1
10 2
11 3


In [261]:
land

array([[1, 2, 3, 5],
       [5, 6, 7, 8],
       [4, 3, 2, 1]])

In [289]:
lll = land[0, :].flatten()
lll.sort()
lll[-2]

3

In [291]:
answer = 0
for i in range(land.shape[0]):
    answer += land[i, :].max()
    l = np.where(land == land[i, :].max())[1][0]
    if l == np.where(land == land[i-1, :].max())[1][0]:
        answer -= land[i, :].max()
        ll = land[i, :].flatten()
        ll.sort()
        answer += ll[-2]
    print(answer)

5
12
16


In [299]:
land = np.array([[1,2,3,5],[5,6,7,8],[4,3,2,1]])
land

array([[1, 2, 3, 5],
       [5, 6, 7, 8],
       [4, 3, 2, 1]])

In [300]:
def solution(land):
    answer = 0
    for i in range(land.shape[0]):
        answer += land[i, :].max()
        l = np.where(land == land[i, :].max())[1][0]
        if l == np.where(land == land[i-1, :].max())[1][0]:
            answer -= land[i, :].max()
            ll = land[i, :].flatten()
            ll.sort()
            answer += ll[-2]
            
    print('Hello Python')
    return answer

In [301]:
solution(land)

Hello Python


16